#!/bin/bash

set -ex

targets=(
    aarch64-unknown-linux-gnu
    aarch64-unknown-linux-musl
    arm-unknown-linux-gnueabi
    arm-unknown-linux-gnueabihf
    armv4t-unknown-linux-gnueabi
    armv5te-unknown-linux-gnueabi
    armv5te-unknown-linux-uclibcgnueabi
    armv7-unknown-linux-gnueabi
    armv7-unknown-linux-gnueabihf
    avr
    i586-unknown-linux-gnu
    i586-unknown-linux-musl
    i686-unknown-linux-gnu
    i686-unknown-linux-musl
    i686-w64-mingw32
    mips64el-unknown-linux-gnuabi64
    mips64el-unknown-linux-musl
    mips64-unknown-linux-gnuabi64
    mips64-unknown-linux-musl
    mipsel-unknown-linux-gnu
    mipsel-unknown-linux-musl
    mipsel-unknown-linux-uclibc
    mipsisa32r6el-unknown-linux-gnu
    mipsisa32r6-unknown-linux-gnu
    mipsisa64r6el-unknown-linux-gnuabi64
    mipsisa64r6-unknown-linux-gnuabi64
    mips-unknown-linux-gnu
    mips-unknown-linux-musl
    mips-unknown-linux-uclibc
    powerpc64le-unknown-linux-gnu
    powerpc64le-unknown-linux-musl
    powerpc64-unknown-linux-gnu
    powerpc64-unknown-linux-musl
    powerpc-unknown-linux-gnu
    powerpc-unknown-linux-musl
    riscv32-unknown-linux-gnu
    riscv64-unknown-linux-gnu
    s390x-unknown-linux-gnu
    sparc64-unknown-linux-gnu
    sparc-unknown-linux-gnu
    x86_64-unknown-linux-gnu
    x86_64-unknown-linux-gnux32
    x86_64-unknown-linux-musl
    x86_64-w64-mingw64
)

mkdir -p 'done'
for target in ${targets[@]}; do
    if [[ ! -e done/$target ]]; then
        "$(dirname "$(realpath "$0")")/build" $target
    fi
done

ln -sfn x86_64-w64-mingw64 x86_64-pc-windows-gnu
ln -sfn i686-w64-mingw32 i686-pc-windows-gnu
ln -sfn avr avr-unknown-unknown
